# Tak musimy tutaj definiować naszą maszynę
# Podajemy:
# Nazwa hosta, IP, port, user, ścieżka do klucza prywatnego
# jenkins ansible_host=145.239.83.229 ansible_port=22 ansible_user=root ansible_private_key_file=/Users/karol/.ssh/id_rsa
#
# Jednak nie musimy tego podawać za każdym razem. Możemy sobie zdefiniować plik ansible.cfg, w którym podamy zmienne,
# które będą używane w każdorazowym łączeniu się do maszyny zdalnej
# jenkins ansible_host=145.239.83.229 ansible_port=22

# Typowa notacja dla plików .ini 
# W nawiasach kwadratowych definiujemy nazwę grupy hostów
[webservers]
jenkins        ansible_host=145.239.83.229 ansible_port=22
registry       ansible_host=51.91.100.185  ansible_port=22
easeci-core    ansible_host=51.254.33.28   ansible_port=22
easeci-client  ansible_host=164.132.55.26  ansible_port=22
easeci-website ansible_host=164.132.55.28  ansible_port=22
