# Tak musimy tutaj definiować naszą maszynę
# Podajemy:
# Nazwa hosta, IP, port, user, ścieżka do klucza prywatnego
# jenkins ansible_host=145.239.83.229 ansible_port=22 ansible_user=root ansible_private_key_file=/Users/karol/.ssh/id_rsa
#
# Jednak nie musimy tego podawać za każdym razem. Możemy sobie zdefiniować plik ansible.cfg, w którym podamy zmienne,
# które będą używane w każdorazowym łączeniu się do maszyny zdalnej
# jenkins ansible_host=145.239.83.229 ansible_port=22

# Typowa notacja dla plików .ini 
# W nawiasach kwadratowych definiujemy nazwę grupy hostów
[webservers]
jenkins        ansible_host=145.239.83.229 ansible_port=22
registry       ansible_host=51.91.100.185  ansible_port=22
easeci-core    ansible_host=51.254.33.28   ansible_port=22
easeci-client  ansible_host=164.132.55.26  ansible_port=22
easeci-website ansible_host=164.132.55.28  ansible_port=22

# Mozemy uzywać rónych parametrów dla kazdego wpisu inventory
# To tak zwane "behavioral inventory parameters" czyli np. ansible host, ansible_port czy ansible_password

# Mozna takze definiować grupy grup, istnieje do tego dedykowana składnia
# Pod nazwę 'grupa' mozemy sobie wstawic nazwę jaką chcemy
[grupa:children]
webservers

# Jeśli mamy grupy serwerów, które są nazywane z kolejnymi numerami, etc.
# Mozemy wymieniać wszystkie za pomocą takiego zapisu:
[web] 
web[01:20].staging.pl
# Wówczas zostaną wyliczone serwery od 01 do 20
# Działa to takze z literami


# Bardzo ciekawą i za pewne bardzo przydatną rzeczą jest ustawianie zmiennych przypisanych dla jakiejś grupy.
# Jaki problem to rozwiązuje?
# Np. jak mamy kilkanaście serwerów postgresql oraz rabbita, to kazda grupa kozysta z innego portu etc.
# Aby zdefiniować zmienne dla grupy, wystarczy po dwukropku wstawić 'vars'
[db]
db[01:05].postgres.staging.lublin.pl
# A teraz odnosimy się do wyzej zdefiniowanej grupy o nazwie 'db' i przypisujemy kilka zmiennych
[db:vars]
db_username=admin
db_password=admin1234
db_port=5432

# Zwróć uwagę na dwa nowe katalogi:
# host_vars  - umieszczać będziemy tutaj zmienne dla kazdego hosta z osobna
# group_vars - tutaj mozemy umieszczać zmienne powiązane z daną grupą hostów
# Dlaczego?
# Wydzielamy specjalne katalogi na zmienne, poniewaz jeden plik inventory byłby zbyt długi i skomplikowany
#
# Następnie tworzymy pliki o nazwie takiej, jaką ma dana grupa w inventory