Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.34.1"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" 
    end
  end

  config.vm.define "host01" do |host01|
    host01.vm.hostname = "host01"
    host01.vm.network "private_network", ip: "192.168.34.2"
    host01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "host02" do |host02|
    host02.vm.hostname = "host02"
    host02.vm.network "private_network", ip: "192.168.34.3"
    host02.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "host03" do |host03|
    host03.vm.hostname = "host03"
    host03.vm.network "private_network", ip: "192.168.34.4"
    host03.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "host04" do |host04|
    host04.vm.hostname = "host04"
    host04.vm.network "private_network", ip: "192.168.34.5"
    host04.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "host05" do |host05|
    host05.vm.hostname = "host05"
    host05.vm.network "private_network", ip: "192.168.34.6"
    host05.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end
end
